/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridelabz.employeepayroll;

import org.junit.Test;

import com.bridgelabz.employeepayroll.Employee;
import com.bridgelabz.employeepayroll.EmployeePayrollService;

import static org.junit.Assert.*;

import java.util.List;

public class EmployeePayrollTest {

	@Test
	public void givenEmployeePayrollInDB_WhenRetrieved_ShouldPassTheTest() {
		EmployeePayrollService employeePayrollService = new EmployeePayrollService();
		List<Employee> employeePayrollData = employeePayrollService.readEmployeePayrollData();
		assertEquals(3, employeePayrollData.size());
 	}
}
