/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridelabz.employeepayroll;

import org.junit.Test;

import com.bridgelabz.employeepayroll.Employee;
import com.bridgelabz.employeepayroll.EmployeePayrollService;
import com.bridgelabz.employeepayroll.SQLCustomException;

import static org.junit.Assert.*;

import java.util.List;

public class EmployeePayrollTest {

	@Test
	public void givenEmployeePayrollInDB_WhenRetrieved_ShouldPassTheTest() {
		EmployeePayrollService employeePayrollService = new EmployeePayrollService();
		List<Employee> employeePayrollData = employeePayrollService.readEmployeePayrollData();
		assertEquals(3, employeePayrollData.size());
 	}
	
	@Test
	public void givenNewSalary_WhenUpdated_ShouldSyncWithTheDatabase() {
		EmployeePayrollService employeePayrollService = new EmployeePayrollService();
		List<Employee> employeePayrollData = employeePayrollService.readEmployeePayrollData();
		try {
			employeePayrollService.updateSalary("Terisa", 3000000);
			boolean result  = employeePayrollService.checkEmployeePayrollInSyncWithDB("Terisa");
			assertTrue(result);
		} catch (SQLCustomException e) {
			e.printStackTrace();
		}
		
	}
}
