/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package employeepayroll;

import org.junit.Test;

import com.bridgelabz.employeepayroll.EmployeePayrollService;

import static org.junit.Assert.*;

public class EmployeePayrollTest {
	
    @Test public void givenEmployeePayrollInDB_WhenRetrieved_ShouldPassTheTest() {
    	System.out.println("Welcome To employee payroll service");
    }
}
