/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.employeepayroll;

import java.util.List;

public class EmployeePayrollService {
    private List<EmployeePayrollService> employeePayrollList;

	public boolean someLibraryMethod() {
        return true;
    }

	public List<EmployeePayrollService> readEmployeePayrollData() {
		this.employeePayrollList  = new EmployeePayrollDBService().readData();
		return this.readEmployeePayrollData();
	}
}
